WITH EXAMRECORDS AS (
    SELECT S.STUDENT_ID, S.STUDENT_NAME, SUB.SUBJECT_NAME
    FROM STUDENTS S
    CROSS JOIN SUBJECTS SUB
)
SELECT 
    ER.STUDENT_ID,
    ER.STUDENT_NAME,
    ER.SUBJECT_NAME,
    COUNT(E.SUBJECT_NAME) AS ATTENDED_EXAMS
FROM EXAMRECORDS ER
LEFT JOIN EXAMINATIONS E
ON ER.STUDENT_ID = E.STUDENT_ID 
AND ER.SUBJECT_NAME = E.SUBJECT_NAME
GROUP BY ER.STUDENT_ID, ER.STUDENT_NAME, ER.SUBJECT_NAME
ORDER BY ER.STUDENT_ID, ER.SUBJECT_NAME;
